### ISSUE TITLE
Add reusable BPF library/component

### ISSUE THREAD

**Issue by saurabh-dua** [Spirent/openperf#177]
Useful analyzer and capture optimization.  While not strictly necessary, it’s **really** nice to have and I’d like to have an implementation sooner rather than later as it is performance critical and probably complicated.  I think it’s worth having something with which to experiment and iterate.

**Comment by cmyers-spirent** [comment]
Will need a few minor tweaks to support FCS error and TCP/UDP checksum error filtering
