### ISSUE TITLE
OpenPerf docker runtime image for cloud-native deployments

### ISSUE THREAD

**Issue by jhiga** [Spirent/openperf#250]
Provide the ability for consumers to easily deploy an OpenPerf pod in a k8s cluster.

Today there is Dockerfile for the OpenPerf build environment.  However, this issue is focused on the OpenPerf runtime container image that starts the API server on startup.

Question:  What docker repo can we use to host this image?

**Comment by jhiga** [comment]
Initially provide a tgz container image.  We'll figure out which repo to use later.

**Comment by abelov-spirent** [comment]
estimate 1d
