### ISSUE TITLE
Optimize memory buffer initialization

### ISSUE THREAD

**Issue by jhiga** [Spirent/openperf#259]
The assumption here is that OpenPerf generates the randomized sequence indexes before the test begins which causes it to be a bottleneck.

The following are optimizations suggested by @DerangedMonkeyNinja :
- Use a pseudo-random generation for the setup to speed things up on platforms with slow hardware random number generators (RNG’s).
- Use a dedicated thread to generate sequence indexes and write them to a ring buffer for the I/O thread to use.

Suggest consulting with @DerangedMonkeyNinja prior to starting work on this issue.

**Comment by jhiga** [comment]
Must also consider (and test) the scenario of switching the access pattern from random to sequential.

**Comment by loskutnikov-spirent** [comment]
Preliminary estimate: 1 day
Estimate may be changed after investigations and determining the root cause of the issue
