### ISSUE TITLE
Memory generator should allow for pre-allocation of test buffer

### ISSUE THREAD

**Issue by jhiga** [Spirent/openperf#264]
OpenPerf uses `mmap` to allocate the memory buffer when creating the load config and the kernel doesn't actually allocate the memory until it writes due to Linux using lazy memory allocation.

The ask is to provide an option to pre-allocate the specified buffer size (e.g. writing a single byte to each memory page to cause the memory to be allocated before the generator starts).

**Use-case**
In a storage test on a system with large caches, unless the agent pre-allocates memory, the underlying storage driver will use the available free memory as cache and storage I/O operations end up hitting the cache. Therefore, the IOPS/bandwidth results are extremely fast.  They do not test the access of the external storage system.

**Comment by loskutnikov-spirent** [comment]
Estimate: 2d

**Comment by DerangedMonkeyNinja** [comment]
I think this behavior should be mandatory, not optional.  The intent is to actually allocate the memory requested by the user.

**Comment by jhiga** [comment]
Yes, I agree.  Apologies for not phrasing that properly in the description.
