### ISSUE TITLE
Workload (TVLP) playback

### ISSUE THREAD

**Issue by jhiga** [Spirent/openperf#278]
Time Varying Load Profile (TVLP) provides a mechanism to program an OpenPerf instance to programmatically independently perform CPU, memory, network, storage configuration adjustments at specific times.  The use-case is to simulate a more realistic VNF/CNF workload.

Preliminary estimate: 22d
1. Make REST API Specification(1d).
2. Integrate LuaJIT into OpenPerf (1d).
3. Migrate LUA launcher (3d).
4. Adopt common Inception LUA scripts (2d).
5. Add REST handler (2d).
6. Migrate TVLP. (10d*).
7. Make AAT and Unit tests (2d).
8. Make documentation (1d).
\* This is a preliminary estimate. Because architectures of OpenPerf and Inception are different, we cannot simply transfer the module as-is.  We should make some changes to fit the new architecture and API.  Estimate may change after completing task no. 1.

**Comment by jhiga** [comment]
@DerangedMonkeyNinja Before starting any development, I'd like to get your thoughts on whether it's feasible to migrate the existing TVLP implementation in Inception over to OpenPerf to fit the current architecture or if you feel it needs to be re-designed from the ground up or something in-between.

**Comment by jhiga** [comment]
According to @DerangedMonkeyNinja anything related to Lua/LuaJIT should be scrapped, so 2 - 4 (in preliminary estimates) go away.

**Comment by abelov-spirent** [comment]
@jhiga @DerangedMonkeyNinja  I have prepared approximate scheme of TVLP module. 
![image](https://user-images.githubusercontent.com/60749064/88678807-05ce1180-d119-11ea-88cf-001b75af66ac.png)
Also pull request with draft API is created (#294). I will recalculate estimates after we approve API.

**Comment by abelov-spirent** [comment]
estimate: 18d

Make REST API Specification(1d).
Add REST handler (2d).
Migrate TVLP. (10d*)
Dynamic TVLP module linking (1d)
Make AAT and Unit tests (3d).
Make documentation (1d)
