### ISSUE TITLE
Add rate fields to the results (BlockGeneratorStats/MemoryGeneratorStats/CpuGeneratorTargetStats )

### ISSUE THREAD

**Issue by clintyoshimura** [Spirent/openperf#342]
We would like to add ops_rate, bytes_rate, and latency_average to BlockGeneratorStats and MemoryGeneratorStats.

**Comment by DerangedMonkeyNinja** [comment]
This is not necessary.  All results have total counts and total time.  Calculating any average value is a simple job for the client, so explicit averages are not necessary.  This is intentional.

**Comment by clintyoshimura** [comment]
Where does the total time come from? I see timestamp, but no total time here: https://github.com/Spirent/openperf/blob/master/tests/aat/api/v1/docs/BlockGeneratorResult.md

**Comment by DerangedMonkeyNinja** [comment]
Oops. I'm getting result sets confused.  The packet {generator, analyzer} have first result/last result to allow calculating averages.  I suggest adding a first result timestamp to the other generator results so that clients can do the same for them.

**Comment by clintyoshimura** [comment]
If we went with this approach, would we be able to configure a byte rate and op rate in t-digest?

**Comment by loskutnikov-spirent** [comment]
You can receive timestamp from the `start` call result. Is not fit for you?

**Comment by DerangedMonkeyNinja** [comment]
You can already configure byte and op rate in t-digest results.  Just use the `dxdt` function for your statistic.

**Comment by clintyoshimura** [comment]
Ah ok that looks like the DXDT t-digest works ok so we can go with that for that issue. Ideally we'd like to have everything we need to calculate the rate in the same message so we don't have to worry about being out of sync or missing messages or anything like that. So if we could get either spent_time or the start and current timestamp in the results that would be good.

**Comment by clintyoshimura** [comment]
We will also need something similar for CpuGeneratorTargetStats so we can calculate operations/sec

**Comment by DerangedMonkeyNinja** [comment]
@loskutnikov-spirent I think `spent_time` has some adverse side effects.  The rationale for including a timestamp with all results is so that results can be plotted on a graph.  Using an elapsed counter introduces sync issues when looking at stats from different generators.  If the start call returns a timestamp, then clients should be able to calculate the elapsed time and still use the `now` timestamps in results to plot, so...  we can just leave those as is?

**Comment by clintyoshimura** [comment]
Sorry, for CpuGeneratorTargetStats I meant we needed the start timestamp for that result too so we can calculate the rate for the results. Not the t-digest.

**Comment by clintyoshimura** [comment]
Even if the start call returns a timestamp, I still prefer to have everything needed to calculate a rate in a single stand alone result message. Its just easier when debugging and there's no uncertainty that the client/server are using different starting timestamps.
