### ISSUE TITLE
Add the System load capability for CPU Generator

### ISSUE THREAD

**Issue by loskutnikov-spirent** [Spirent/openperf#343]
Add additional top-level field into CPU Generator configuration to specify the overall system load, instead of per core load.
This field will be named `utilization` object. 
User should use only one of `utilization` or `cores` fields in configuration.

When `utilization` value is specified, OpenPerf creates one thread to each available CPU core and apply this value to them. 
For system load mode will be used `scalar` instruction set.

**Comment by loskutnikov-spirent** [comment]
There are two variants for the `utilization` field value.

1. Range from `0` to `100`. Conforms with per core configuration and this value will applied for each core directly. More convenient for user, in my opinion.
2. Range from `0` to `100 * core_count`. Not so obvious as previous. Requires some calculation from user and knowledge about cores count, but gives some compatibility with `top` and `htop` utilities output.

What do you think @jhiga, @DerangedMonkeyNinja?

**Comment by DerangedMonkeyNinja** [comment]
I expect this sort of stuff to happen in clients, not openperf itself.  Division isn't particularly complex, and the changes in PR#346 make the configuration less explicit since the configuration now has to deal with state. I guess I don't think it's necessary?

**Comment by loskutnikov-spirent** [comment]
It is needed to introduce another mode of the OpenPerf work. This mode will include the PID control and accounting of the load of another OpenPerf threads. The behaviour of this mode will same as Inception CPU generator.

**Comment by jhiga** [comment]
Re: the two variants for the `utilization` field value, I would go with option 2 (range from `0` to `100 * core_count`) since that represents the total desired overall system/process load and aligns with the intent of this new mode.
