### ISSUE TITLE
[dpdk] Can not receive any packet when using DPDK user-mode

### ISSUE THREAD

**Issue by ronanjs** [Spirent/openperf#402]
When configuring the interface in kernel bypass mode, the packets can be sent and received

```
0000:02:00.0 'I350 Gigabit Network Connection 1521' if=enp2s0f0 drv=igb unused=vfio-pci *Active*
```

But when configuring in DPDK mode using `vfio-pci` packets can not be received.

The issue can be reproduced on Shaowei's setup

**Comment by DerangedMonkeyNinja** [comment]
This appears to be specific to the DPDK IGB driver, as 1) there is definitely a bug there and 2) I've verified this issue doesn't happen with other drivers.

**Comment by ronanjs** [comment]
Can not reproduce with the lastest fix
