### ISSUE TITLE
libopenperf_tvlp.so does not work in release mode

### ISSUE THREAD

**Issue by dlutton** [Spirent/openperf#426]
When you build OpenPerf with `MODE=release`, the libopenperf_tvlp.so that gets created will not work with the openperf binary that gets created.

You can create the TVLP generator, however when you run it, it'll immediately stop and the results only returns an `id` and `tvlp_id`.

What's interesting is that if you use the libopenperf_tvlp.so that gets generated from a non release mode with the OpenPerf binary from release mode, TVLP will work.

**Doesn't work:**
```sh
/opt/openperf/build/openperf-linux-x86_64-release/bin$ sudo ./openperf -core.log.level debug --modules.packetio.dpdk.no-init -p 9000 -L "libopenperf_tvlp.so" -m "/opt/openperf/build/openperf-linux-x86_64-release/plugins
" >> ~/openperf.log 2>&1
```
Results from TVLP generator with no errors being thrown:
```json
{
  "id": "43d22d37-13a2-454d-53cd-b8318bb8b5db",
  "tvlp_id": "tvlp-1"
}
```

============================================================================

**This does work (openperf from release mode and libopenperf_tvlp.so from test mode):**
```sh
/opt/openperf/build/openperf-linux-x86_64-release/bin$ sudo ./openperf -core.log.level debug --modules.packetio.dpdk.no-init -p 9000 -L "libopenperf_tvlp.so" -m "/opt/openperf/build/openperf-linux-x86_64-testing/plugins
" >> ~/openperf.log 2>&1
```

**and this also works (full test mode):**

```sh
/opt/openperf/build/openperf-linux-x86_64-testing/bin$ sudo ./openperf -core.log.level debug --modules.packetio.dpdk.no-init -p 9000 -L "libopenperf_tvlp.so" -m "/opt/openperf/build/openperf-linux-x86_64-testing/plugins" >> ~/openperf.log 2>&1
```
Results are generated successfully

**Comment by loskutnikov-spirent** [comment]
Confirmed. Fix will be soon published.
