### ISSUE TITLE
The default for flow_counters in the swagger schema is set to a list instead of a scalar.

### ISSUE THREAD

**Issue by clintyoshimura** [Spirent/openperf#470]
In the definition of flow_counters  in api/schema/v1/modules/packet/analyzer.yaml, the default is set to a list instead of a scalar (its an string enum type). ie) Its set to:
          default:
            - frame_count
instead of:
          default: frame_count

**Comment by DerangedMonkeyNinja** [comment]
Yes; this is intentional.  You can add any set of flow counters you want to the list.
